package xyz.ixidi.jumi.riotapi.entity

data class LolChampionSelectSummoner(
    val actingBackgroundAnimationState: String,
    val activeActionType: String,
    val areSummonerActionsComplete: Boolean,
    val assignedPosition: String,
    val banIntentSquarePortratPath: String,
    val cellId: Long,
    val championIconStyle: String,
    val championName: String,
    val currentChampionVotePercentInteger: Int,
    val entitledFeatureType: String,
    val isActingNow: Boolean,
    val isDonePicking: Boolean,
    val isOnPlayersTeam: Boolean,
    val isPickIntenting: Boolean,
    val isPlaceholder: Boolean,
    val isSelf: Boolean,
    val pickSnipedClass: String,
    val shouldShowActingBar: Boolean,
    val shouldShowBanIntentIcon: Boolean,
    val shouldShowExpanded: Boolean,
    val shouldShowRingAnimations: Boolean,
    val shouldShowSelectedSkin: Boolean,
    val shouldShowSpells: Boolean,
    val showMuted: Boolean,
    val showTrades: Boolean,
    val skinId: Int,
    val skinSplashPath: String,
    val slotId: Int,
    val spell1IconPath: String,
    val spell2IconPath: String,
    val statusMessageKey: String,
    val summonerId: Long,
    val tradeId: Long
)